---
title: "Using metabalize"
author: "Andrew D. Steen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using metabalize}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

# Introduction
This document shows (currently in a very rough way) how to run `metabalize` to calculate exponential fits for flux data.

```{r}
library(ggplot2)
library(plyr)
library(reshape2)
#require(devtools)
#load_all
library(metabalize)

raw_list <- read_MAVEN(data_fn="../data/140114_AET_13C_glucose_flux.csv",
                  key_fn="../data/curacao_samplekey.csv")

# Split the data from the experimental variables metadata
#    I should probably change the exp.var workflow
raw <- raw_list$raw_data
exp.var <- raw_list$exp.var


# Convert replicate variable into factor - not sure how
raw$replicate <- as.factor(raw$replicate)

################
# Create data frame of only 12C isotopomers; expressed as fraction of total ions 
################
```
## Identify 12C isotopomers, remove all others.
```{r}
# calc_12C identifies 12C ions
system.time({
  raw_12C <- calc_12C(raw) 
}) # about 6 seconds on my macbook air

# Filter 12C peaks from 13C-containing peaks
C12_only <- subset(raw_12C, is.12C==TRUE)
```
## Fit exponential models
```{r}
################
# Fit exp models to each unique sample, metabolite, treatment & sample.type
################

min_for_debugging <- C12_only[ , c("compound", "treatment", "sample.type", "time", "relative.ion.count")]
system.time({ # This throws an error - I don't know why
  nls_fits <- dlply(min_for_debugging, #C12_only,
                    c("compound", "treatment", "sample.type"), safe_NLS, .inform=TRUE)
}) # ~1.4 seconds on my laptop, not so bad

# Note that in some cases, no model was created. 
# How many bad models were created?
bad_fits <- ldply(nls_fits, anyNA)
sum(bad_fits$V1)/nrow(bad_fits) #23.4% of the cases couldn't be fit to an exponential model
```


# Getting the data out
```{r}
# Get the nls coefficients out
all_coefs <- ldply(nls_fits, function(x) exp_coef(x))
print(all_coefs)

# How many of the A values are good?
ggplot(all_coefs, aes(x=A.est)) + 
  geom_density() #Many are close to zero

# Create predicted values for exponential fit
all_preds <- ldply(nls_fits, safe_NLS_pred, c(0, 125))

# Plot all the data
ggplot() +
  geom_point(data=C12_only, aes(x=time, y=relative.ion.count, colour=sample.type)) + 
  geom_line(data=all_preds, aes(x=time, y=relative.ion.count, colour=sample.type)) + 
  facet_wrap(~compound)
ggsave("../testplot.png", height=20, width=20, units="in", dpi=300, type="cairo")
p <- plot_timecourse(C12_only, 
                     exp.var=c("compound", "treatment", "sample.type", "time"),
                     exp_pred=all_preds)
# print(p)

```

